# Generated by Django 4.2 on 2024-04-01 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sporty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('contact_email', models.CharField(max_length=200, verbose_name='Contact Email')),
                ('is_active', models.BooleanField(default=False)),
                ('about', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=200, null=True)),
                ('description', models.TextField(blank=True, default=None, max_length=200, null=True)),
                ('sports', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='workout_app.sporty')),
            ],
        ),
        migrations.CreateModel(
            name='Athelete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200, verbose_name='Email')),
                ('sport', models.CharField(choices=[('Track and Field', 'Basketball')], max_length=200)),
                ('sports', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='workout_app.sporty')),
            ],
        ),
    ]
