# Generated by Django 4.2 on 2024-04-01 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sporty',
            new_name='AtheleteProgess',
        ),
        migrations.RenameField(
            model_name='athelete',
            old_name='sports',
            new_name='athelete_progess',
        ),
        migrations.RenameField(
            model_name='workout',
            old_name='sports',
            new_name='athelete_progess',
        ),
    ]
